Repository dotmind/blink, pull requests merged in 2023-01, with the labels that each got.

#71 [APP] Improve ligthouse score & global perf 🚀
  index.html
  package-lock.json
  package.json
  public/manifest.json
  public/robots.txt
  public/sw.js
  src/app/assets/lottie/loader.json
  src/app/assets/lottie/success-confetti.json
  src/app/components/About/index.tsx
  src/app/components/Loader.tsx
  src/app/components/Loader/index.tsx
  src/app/components/Loader/styles.module.scss
  src/app/components/Logo/index.tsx
  src/app/components/SuccessConfetti.tsx
  src/app/hooks/useWindowSize.ts
  src/app/services/abla.ts
  src/app/services/serviceworker.ts
  src/app/styles/fonts.scss
  src/main.tsx
  src/modules/upload/components/UploadFile/index.tsx
  vite.config.ts
Labels: Enhancement

#72 [APP] Lazy load tab content ⏳
  package-lock.json
  package.json
  src/app/components/Head.tsx
  src/app/components/Router.tsx
  src/app/components/TabSelector/index.tsx
  src/app/pages/Home.tsx
Labels: Enhancement, GTG

#74 [FRAME] Load document in frame preview 🪟
  package-lock.json
  src/app/components/Drawer/index.tsx
  src/app/components/Drawer/styles.module.scss
  src/app/components/History/index.tsx
  src/app/components/History/styles.module.scss
  src/app/components/Loader/styles.module.scss
  src/app/hooks/useWindowSize.ts
  src/app/languages/en/translations.json
  src/app/languages/fr/translations.json
  src/app/pages/Home.tsx
  src/app/pages/Preview.tsx
  src/app/providers/DrawerProvider.tsx
  src/app/services/navigator.ts
  src/modules/download/components/Document/index.tsx
  src/modules/download/components/Document/styles.module.scss
  src/modules/download/components/Download/index.tsx
  src/modules/download/components/Download/styles.module.scss
  src/modules/download/components/FileViewer/index.tsx
  src/modules/download/components/FileViewer/styles.module.scss
  src/modules/download/providers/DownloadProvider.tsx
  src/modules/upload/components/UploadFile/index.tsx
  src/modules/upload/components/UploadFile/styles.module.scss
Labels: Feature, GTG
